# Generated by Django 2.0.6 on 2020-02-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0005_auto_20200228_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='fecha_de_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AddField(
            model_name='libro',
            name='fecha_de_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de creacion'),
        ),
    ]
