# Generated by Django 2.0.6 on 2020-03-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0007_libro_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='estado',
        ),
        migrations.AddField(
            model_name='autor',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
